In [2]:
#TASK-01
import numpy as np
a=np.array([[1,2,3] ,[4,5,6], [7,8,0]])
a=np.sort(a)
a=a.flatten()
a=np.sort(a)
a=a.reshape(3,3)
a[a>5]=a[a>5]**2
print("array after squaring values >5")
print(a)

array after squaring values >5
[[ 0  1  2]
 [ 3  4  5]
 [36 49 64]]


In [2]:
#TASK-02
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
#INCOMPLETE
#print(a) final result...

[1 2 3 4 5]


In [3]:
#TASK-03
import numpy as np
a=np.linspace(5,50,10)
a=a.astype(int)
print(a)
sum=a.sum()
print("sum of array is",sum)

[ 5 10 15 20 25 30 35 40 45 50]
sum of array is 275


In [4]:
#TASK-04
import pandas as pd
df=pd.DataFrame({"scores":[70,75,80,100,78,82,89,54]})
df["GRADES"]=["A" if x>=80 else "B" for x in df["scores"]]
print(df)

   scores GRADES
0      70      B
1      75      B
2      80      A
3     100      A
4      78      B
5      82      A
6      89      A
7      54      B


In [ ]:
#TASK-05:
df[(df['scores'] > 70) & (df['scores'] < 90)]['scores']

In [ ]:
#TASK-06
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Grade': ['A', 'B', 'A', 'C', 'B'],
    'Score': [85, 90, 88, 76, 95]
}
df = pd.DataFrame(data)
grouped = df.groupby('Grade')['Score'].mean().reset_index()
grouped.to_csv('grouped_scores.csv', index=False)
print(grouped)


In [ ]:
#TASK-07
df=pd.DataFrame([1,None ,3,4,5,7,None,None,12,32],columns=["scores"])
mean=df["scores"].mean()
print(df)
df["scores"]=df["scores"].fillna(mean)
print(df)


In [1]:
#TASK-08
import pandas as pd
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve', 'David'],
    'Salary': [50000, 60000, 52000, 62000]
})

# Merging the DataFrames on the 'Name' column
result = pd.merge(df1, df2, on='Name')

# Display the merged DataFrame
print(result)

    Name  Age  Salary
0  Alice   24   50000
1    Bob   27   60000
2  David   32   62000
